name: Release

on: push

# on:
#   push:
#     tags:
#       - "v*"

jobs:
  cut-release:
    runs-on: ubuntu-latest
    env:
      GITHUB_REF_MOCK: 'refs/tags/v1.3.0'
      DOCKER_IMAGE: gcr.io/assemble-services/pg-amqp-bridge-node
      BODY_PATH: release-body.txt
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set output
        id: vars
        run: echo ::set-output name=tag::${GITHUB_REF_MOCK#refs/tags/} && echo ::set-output name=version::${GITHUB_REF_MOCK#refs/tags/v}
      - name: Generate Docker image tag
        env:
          RELEASE_VERSION: ${{ steps.vars.outputs.version }}
        run: echo "$DOCKER_IMAGE:$RELEASE_VERSION" > $BODY_PATH
      - name: Generate Changelog
        env:
          RELEASE_VERSION: ${{ steps.vars.outputs.version }}
        run: awk "/[#]{2,3} \[$RELEASE_VERSION/{flag=1; next} /[#]{2,3} \[/{flag=0} flag" CHANGELOG.md >> $BODY_PATH
      - name: Print Body
        run: cat $BODY_PATH
      - name: Release
        uses: softprops/action-gh-release@v1
        # if: startsWith(github.ref, 'refs/tags/')
        with:
          name: Version ${{ steps.vars.outputs.version }}
          tag_name: ${{ steps.vars.outputs.tag }}
          body_path: $BODY_PATH
          draft: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
